### ISSUE TITLE
Service to update all data when back online / ha restart

### ISSUE THREAD

**Issue by nagyrobi** [dgomes/hasp-lvgl-custom-component#5]
After reboot of hasp-lvgl, current data is lost.
However, on MQTT availability state can be tracked, so a simple automation which could check state from Unavailable to Available could push all the related data to reflect the state.

**Comment by dgomes** [comment]
I think here I'm going to subscribe to hasp-lvgl LWT and upon state change to online will push everything.

(Please note that I'm currently working in a new branch https://github.com/dgomes/hasp-lvgl/tree/persistent_entities)

**Comment by nagyrobi** [comment]
Awesome. Just testing it and it works great.
I only hate that after each config change I have to restart HA.

**Comment by nagyrobi** [comment]
> (Please note that I'm currently working in a new branch https://github.com/dgomes/hasp-lvgl/tree/persistent_entities)

Fails with
```
2021-03-04 22:05:51 ERROR (MainThread) [homeassistant.setup] Error during setup of component hasp-lvgl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/hasp-lvgl/__init__.py", line 198, in async_setup
    for plate in config[DOMAIN]:
KeyError: 'hasp_lvgl'
```

**Comment by dgomes** [comment]
Yes... there is a breaking change

your configuration is currently:

"hasp-lvgl" it must now be "hasp_lvgl"

this is a HA requirement not to use "-"

**Comment by nagyrobi** [comment]
Still fails with
```
2021-03-05 11:01:58 ERROR (MainThread) [homeassistant.setup] Error during setup of component hasp_lvgl
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/hasp_lvgl/__init__.py", line 213, in async_setup
    await async_listen_state_changes(hass, track_entity_id, plate, objid)
  File "/config/custom_components/hasp_lvgl/__init__.py", line 106, in async_listen_state_changes
    command_topic = f"{hass.data[DOMAIN][plate]._topic}/command/{obj}.val"
AttributeError: 'dict' object has no attribute '_topic'
```

**Comment by nagyrobi** [comment]
> I think here I'm going to subscribe to hasp-lvgl LWT and upon state change to online will push everything.
 
I tried to find out in the code how to trigger update of all the objects at once but couldn't figure it out. Can you give me a hand on this?

**Comment by dgomes** [comment]
Still work in progress...

**Comment by dgomes** [comment]
e077f18e2cbbc115e5fafdb5d426535f40e5d8de addresses this issue directly

**Comment by nagyrobi** [comment]
Perfect, thanks!
